/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ShopRouteImport } from './routes/shop';
import { Route as ProductProductIdRouteImport } from './routes/product.$productId';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as CartRouteImport } from './routes/cart';
import { Route as CheckoutRouteImport } from './routes/checkout';

const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ShopRoute = ShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => rootRouteImport,
});
const ProductProductIdRoute = ProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const CartRoute = CartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => rootRouteImport,
});
const CheckoutRoute = CheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ShopRoute: ShopRoute,
    ProductProductIdRoute: ProductProductIdRoute,
    AdminRoute: AdminRoute,
    ProfileRoute: ProfileRoute,
    CartRoute: CartRoute,
    CheckoutRoute: CheckoutRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();


