/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ShopRouteImport } from './routes/shop';
import { Route as ProductProductIdRouteImport } from './routes/product.$productId';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as CartRouteImport } from './routes/cart';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy';
import { Route as ReturnCancellationRouteImport } from './routes/return-cancellation';
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy';
import { Route as SitemapRouteImport } from './routes/sitemap';
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions';

const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ShopRoute = ShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => rootRouteImport,
});
const ProductProductIdRoute = ProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const CartRoute = CartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => rootRouteImport,
});
const CheckoutRoute = CheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => rootRouteImport,
});
const ReturnCancellationRoute = ReturnCancellationRouteImport.update({
    id: '/return-cancellation',
    path: '/return-cancellation',
    getParentRoute: () => rootRouteImport,
});
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
    id: '/shipping-policy',
    path: '/shipping-policy',
    getParentRoute: () => rootRouteImport,
});
const SitemapRoute = SitemapRouteImport.update({
    id: '/sitemap',
    path: '/sitemap',
    getParentRoute: () => rootRouteImport,
});
const TermsConditionsRoute = TermsConditionsRouteImport.update({
    id: '/terms-conditions',
    path: '/terms-conditions',
    getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ShopRoute: ShopRoute,
    ProductProductIdRoute: ProductProductIdRoute,
    AdminRoute: AdminRoute,
    ProfileRoute: ProfileRoute,
    CartRoute: CartRoute,
    CheckoutRoute: CheckoutRoute,
    ContactRoute: ContactRoute,
    PrivacyPolicyRoute: PrivacyPolicyRoute,
    ReturnCancellationRoute: ReturnCancellationRoute,
    ShippingPolicyRoute: ShippingPolicyRoute,
    SitemapRoute: SitemapRoute,
    TermsConditionsRoute: TermsConditionsRoute,
};

export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
